module.exports = Object.freeze({

    SQL_ADD_HOUSE: 'CALL ADD_HOUSE(?,?,?,?,?,?,?,?,?,?,?)',
    SQL_UPDATE_MAIN: 'CALL UPDATE_MAIN_IMG(?,?)',
    SQL_PUBLISH_HOUSE: 'CALL PUBLISH_LODGING(?)',
    SQL_ADD_HOUSE_IMG: 'CALL ADD_HOUSEIMAGE(?,?)',


   SQL_GET_LEASES : 'CALL GET_AVAILABLE_LEASES()',
   SQL_GET_HOUSETYPES :'CALL GET_HOUSE_TYPES()',
   SQL_GET_LEASESLOCATION: 'CALL GET_AVAILABLE_LEASES_LOCATIONS()',
   SQL_GET_HOUSE_FULLPLACE: 'CALL GET_HOUSE_FULLPLACE(?)',
   SQL_GET_HOUSE_LOCATION: 'CALL GET_HOUSE_LOCATION(?)',
   SQL_GET_HOST_INFO: 'CALL GET_HOUSE_HOST_INFO(?)',
   SQL_GET_LODGING_PHOTOS: 'CALL GET_HOUSE_PHOTOS(?)',

   SQL_START_CONTRACT: 'CALL START_CONTRACT(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
   SQL_CANCEL_CONTRACT: 'CALL CANCEL_CONTRACT(?)',
   SQL_UPDATE_CONTRACT_STATUS: 'CALL UPDATE_CONTRACT_STATUS(?,?,?)',

   SQL_GET_USER_INFO: 'CALL GET_USER_INFO(?)',


   SQL_AUTH_USER: 'CALL IS_USER_AUTH(?, ?)',
   SQL_REGISTRATION: 'CALL CREATE_ACCOUNT(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
   SQL_LOGIN: 'CALL LOGIN(?,?)',



   SQL_ADD_TOKEN_TO_LOGIN:'CALL UPDATE_TOKEN(?,?,?)',
   SQL_GET_YOUR_OFFERINGS:'CALL GET_OFFERINGS(?,?)',
   SQL_GET_YOUR_TRIPS: 'CALL GET_TRIPS(?,?)',

   SQL_GET_CHAT: 'CALL GET_CHAT(?)', 
   SQL_SEND_MSG: 'CALL SEND_MSG(?,?,?,?)',

   SQL_GET_LODGING_CONTRACT: 'CALL GET_CONTRACTS_ID(?)'
});
